export const MONGO_CONNECTION_NAME = '___MONGO_CONECTION_NAME___';
export const MONGO_MODULE_OPTIONS = '___MONGO_MODULE_OPTIONS___';

export const DEFAULT_MONGO_CONNECTION_NAME = '__DEFAULT_MONGO___';
